#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 23373858051-eutlg5e9islsupbv9633buafnvdqa0pb.apps.googleusercontent.com
#            client-secret: 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
#            scope: openid, profile, email
